### ISSUE TITLE
Explore how to make NFT Catalog permissionless and open

### ISSUE THREAD

**Issue by nvdtf** [onflow/nft-catalog#137]
We need to explore how we can enable everyone to be able to add a new item to the NFT catalog without requiring a review. 
We also need to examine the review process, and make it more open to the community.

**Comment by btspoony** [comment]
In terms of user perception, we can make it feel more permissionless by automation. Here are my two ideas

1. If we can create a checklist of all the tasks that require human view, we can develop a backend service to automate the verification process and send the results to the blockchain. [Thread](https://discord.com/channels/613813861610684416/1129164082256289842/1153972715267571812)
2. We can also maintain the current human view process but add a new list:
  - The list after "Human view" is called the Featured List. (the original list)
  - The list after automatic verification is called the Validated List. (the new list)

**Comment by joshuahannan** [comment]
Can we close this since we've deprecated NFT Catalog in favor of TokenList?
