### ISSUE TITLE
Getting nft catalog on testnet fails

### ISSUE THREAD

**Issue by PeterBenc** [onflow/nft-catalog#156]
### Current Behavior

Getting nft catalog on testnet fails

### Expected Behavior

Getting nft catalog on testnet works

### Steps To Reproduce

1. check console here. https://www.flow-nft-catalog.com/catalog/testnet

### Environment

```markdown
- OS: any
- Node: -
- npm: -
```

### What are you currently working on that this is blocking?

I have a script that fetches the nft catalog, I think that that script fails on `NFTCatalog.getCatalogEntry`

**Comment by joshuahannan** [comment]
We have deprecated NFT Catalog in favor of [TokenList](https://www.flowverse.co/applications/tokenlist) so I am closing this
