### ISSUE TITLE
[BUG] MainNet Contract A.49a7cda3a1eecc29.NFTRetrieval was not staged for Cadence1.0

### ISSUE THREAD

**Issue by ben-graffle** [onflow/nft-catalog#157]
### Current Behavior

MainNet Contract A.49a7cda3a1eecc29.NFTRetrieval was not staged for Cadence1.0 per the following

- https://staging.dnz.dev/index.html
- https://f.dnz.dev/0x49a7cda3a1eecc29/NFTRetrieval

Was this intentional? Or can the logic contained in this contract get updated for Cadence 1.0?

### Expected Behavior

Code from NFTRetrieval should be executable

### Steps To Reproduce

`import NFTRetrieval from 0x49a7cda3a1eecc29` fails in any script run on MainNet

### Environment

```markdown
n/a
```

**Comment by turbolent** [comment]
In general, contracts that were not be updated to Cadence 1.0 will no longer work.

Some pre-1.0 contract functionality will be available, like accessing `FungibleToken.Vault.balance`, or `NonFungibleToken.NFT.id` through [FLIP 282: Import of pre-Cadence 1.0 Programs](https://github.com/onflow/flips/blob/main/cadence/20240726-pre-cadence-1-import.md)
